# Mika's Directional
# https://mikalooloo.github.io/

# Whether this feature is automatically enabled upon joining
# default: true
Coords: true
Direction: true

# The color of the labels ("X:", "Y:", "Z:", "Facing:")
# default: "#FFAA00" (gold)
LabelsColor: "#FFAA00"
# The color of the values (the numbers and direction name)
# default: "#FFFFFF" (white)
ValuesColor: "#FFFFFF"

# Whether a player needs the "MikaDirectional.User" permission
# to change, via commands, their individual values from the above default ones
NeedUserPerms: false
# Whether a player needs the "MikaDirectional.Reload" permission to reload the config via command
NeedReloadPerms: true